"use client";
import storage from "./storage";
import { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { ScatterChart, Scatter, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ReferenceLine, Cell } from "recharts";
import * as Papa from "papaparse";

const C={navy:"#0C1B33",navyMid:"#162847",carltonNavy:"#0E1E2F",carltonSilver:"#A8B5C2",teal:"#2A9D8F",tealDark:"#21867A",tealLight:"#3DBDAD",coral:"#E76F51",coralLight:"#F4A261",gold:"#F4A261",green:"#22C55E",greenDark:"#16A34A",greenBg:"#DCFCE7",red:"#EF4444",redDark:"#DC2626",redBg:"#FEE2E2",amber:"#F59E0B",amberDark:"#D97706",amberBg:"#FEF3C7",blue:"#3B82F6",blueBg:"#DBEAFE",purple:"#8B5CF6",bg:"#F1F5F9",card:"#FFFFFF",text:"#0F172A",textMid:"#475569",textLight:"#94A3B8",border:"#E2E8F0",borderLight:"#F1F5F9",shadow:"0 1px 3px rgba(0,0,0,0.06),0 1px 2px rgba(0,0,0,0.04)"};

const DEFAULT_METRICS=[
  {id:"cmj_jh",cat:"CMJ",name:"Jump Height",unit:"cm",bi:false},{id:"cmj_rsi_mod",cat:"CMJ",name:"RSI-modified",unit:"m/s",bi:false},{id:"cmj_ct",cat:"CMJ",name:"Contraction Time",unit:"ms",bi:false},{id:"cmj_cmd",cat:"CMJ",name:"Countermovement Depth",unit:"cm",bi:false},{id:"cmj_con_pf_bm",cat:"CMJ",name:"Concentric Peak Force/BM",unit:"N/kg",bi:false},{id:"cmj_fzv_bm",cat:"CMJ",name:"Force at Zero Velocity/BM",unit:"N/kg",bi:false},{id:"cmj_con_imp100",cat:"CMJ",name:"Concentric Impulse 100ms",unit:"N s",bi:false},{id:"cmj_con_pv",cat:"CMJ",name:"Concentric Peak Velocity",unit:"m/s",bi:false},{id:"cmj_ecc_pf_bm",cat:"CMJ",name:"Eccentric Peak Force/BM",unit:"N/kg",bi:false},{id:"cmj_ecc_dur",cat:"CMJ",name:"Eccentric Duration",unit:"ms",bi:false},{id:"cmj_ecc_rfd_bm",cat:"CMJ",name:"Eccentric Decel RFD/BM",unit:"N/s/kg",bi:false},{id:"cmj_ecc_pv",cat:"CMJ",name:"Eccentric Peak Velocity",unit:"m/s",bi:false},{id:"cmj_ft_ct",cat:"CMJ",name:"Flight Time:Contraction Time",unit:"ratio",bi:false},{id:"cmj_pp_bm",cat:"CMJ",name:"Peak Power/BM",unit:"W/kg",bi:false},{id:"cmj_ecc_imp_bm",cat:"CMJ",name:"Eccentric Decel Impulse/BM",unit:"N s/kg",bi:false},{id:"cmj_ecc_brk_asym",cat:"CMJ",name:"Ecc Braking Impulse Asym",unit:"%",bi:false},{id:"cmj_con_imp_asym",cat:"CMJ",name:"Concentric Impulse Asym",unit:"%",bi:false},{id:"cmj_ecc_pf_asym",cat:"CMJ",name:"Ecc Peak Force Asym",unit:"%",bi:false},{id:"cmj_ecc_rfd_asym",cat:"CMJ",name:"Ecc Decel RFD Asym",unit:"%",bi:false},
  {id:"slcmj_jh",cat:"SL CMJ",name:"Jump Height",unit:"cm",bi:true},{id:"slcmj_rsi",cat:"SL CMJ",name:"mRSI",unit:"m/s",bi:true},{id:"slcmj_ct",cat:"SL CMJ",name:"Contraction Time",unit:"ms",bi:true},{id:"slcmj_con_dur",cat:"SL CMJ",name:"Concentric Duration",unit:"ms",bi:true},{id:"slcmj_ecc_dur",cat:"SL CMJ",name:"Eccentric Duration",unit:"ms",bi:true},{id:"slcmj_cmd",cat:"SL CMJ",name:"Countermovement Depth",unit:"cm",bi:true},{id:"slcmj_ecc_pf",cat:"SL CMJ",name:"Eccentric Peak Force",unit:"N",bi:true},{id:"slcmj_con_pf",cat:"SL CMJ",name:"Concentric Peak Force",unit:"N",bi:true},{id:"slcmj_ecc_pf_bm",cat:"SL CMJ",name:"Eccentric Peak Force/BM",unit:"N/kg",bi:true},{id:"slcmj_con_pf_bm",cat:"SL CMJ",name:"Concentric Peak Force/BM",unit:"N/kg",bi:true},{id:"slcmj_con_imp",cat:"SL CMJ",name:"Concentric Impulse",unit:"N s",bi:true},{id:"slcmj_ecc_dec_imp",cat:"SL CMJ",name:"Ecc Decel Impulse",unit:"N s",bi:true},{id:"slcmj_fzv",cat:"SL CMJ",name:"Force at Zero Velocity",unit:"N",bi:true},{id:"slcmj_ecc_pv",cat:"SL CMJ",name:"Eccentric Peak Velocity",unit:"m/s",bi:true},{id:"slcmj_con_pv",cat:"SL CMJ",name:"Concentric Peak Velocity",unit:"m/s",bi:true},{id:"slcmj_brk_rfd",cat:"SL CMJ",name:"Ecc Decel RFD",unit:"N/s",bi:true},{id:"slcmj_con_ttpf",cat:"SL CMJ",name:"Concentric Time to Peak Force",unit:"ms",bi:true},
  {id:"dlhop_jh",cat:"DL Hop",name:"Jump Height",unit:"cm",bi:false},{id:"dlhop_rsi",cat:"DL Hop",name:"RSI",unit:"m/s",bi:false},{id:"dlhop_ct",cat:"DL Hop",name:"Contact Time",unit:"ms",bi:false},{id:"dlhop_pf",cat:"DL Hop",name:"Peak Force",unit:"N",bi:false},{id:"dlhop_ft_ct",cat:"DL Hop",name:"FT:CT Ratio",unit:"ratio",bi:false},
  {id:"slhop_jh",cat:"SL Hop",name:"Jump Height",unit:"cm",bi:true},{id:"slhop_rsi",cat:"SL Hop",name:"RSI",unit:"m/s",bi:true},{id:"slhop_ct",cat:"SL Hop",name:"Contact Time",unit:"ms",bi:true},{id:"slhop_pf",cat:"SL Hop",name:"Peak Force",unit:"N",bi:true},
  {id:"dldj_jh",cat:"DL Drop Jump",name:"Jump Height",unit:"cm",bi:false},{id:"dldj_rsi",cat:"DL Drop Jump",name:"RSI",unit:"m/s",bi:false},{id:"dldj_ct",cat:"DL Drop Jump",name:"Contact Time",unit:"ms",bi:false},{id:"dldj_pf",cat:"DL Drop Jump",name:"Peak Landing Force",unit:"N",bi:false},{id:"dldj_stiff",cat:"DL Drop Jump",name:"Stiffness",unit:"N/m",bi:false},
  {id:"sldj_jh",cat:"SL Drop Jump",name:"Jump Height",unit:"cm",bi:true},{id:"sldj_rsi",cat:"SL Drop Jump",name:"RSI",unit:"m/s",bi:true},{id:"sldj_ct",cat:"SL Drop Jump",name:"Contact Time",unit:"ms",bi:true},{id:"sldj_pf",cat:"SL Drop Jump",name:"Peak Landing Force",unit:"N",bi:true},
  {id:"knee_iso_pf",cat:"ISO - Knee",name:"Peak Force",unit:"N",bi:true},{id:"knee_iso_rpf",cat:"ISO - Knee",name:"Peak Force/BM",unit:"N/kg",bi:true},{id:"knee_iso_f50",cat:"ISO - Knee",name:"Force at 50ms",unit:"N",bi:true},{id:"knee_iso_f100",cat:"ISO - Knee",name:"Force at 100ms",unit:"N",bi:true},{id:"knee_iso_f200",cat:"ISO - Knee",name:"Force at 200ms",unit:"N",bi:true},{id:"knee_iso_imp100",cat:"ISO - Knee",name:"Impulse 100ms",unit:"N s",bi:true},{id:"knee_iso_netpf",cat:"ISO - Knee",name:"Net Peak Force",unit:"N",bi:true},{id:"knee_iso_ttpf",cat:"ISO - Knee",name:"Time to Peak Force",unit:"s",bi:true},
  {id:"ankle_iso_pf",cat:"ISO - Ankle",name:"Peak Force",unit:"N",bi:true},{id:"ankle_iso_rpf",cat:"ISO - Ankle",name:"Peak Force/BM",unit:"N/kg",bi:true},{id:"ankle_iso_f50",cat:"ISO - Ankle",name:"Force at 50ms",unit:"N",bi:true},{id:"ankle_iso_f100",cat:"ISO - Ankle",name:"Force at 100ms",unit:"N",bi:true},{id:"ankle_iso_f200",cat:"ISO - Ankle",name:"Force at 200ms",unit:"N",bi:true},{id:"ankle_iso_imp100",cat:"ISO - Ankle",name:"Impulse 100ms",unit:"N s",bi:true},{id:"ankle_iso_netpf",cat:"ISO - Ankle",name:"Net Peak Force",unit:"N",bi:true},{id:"ankle_iso_ttpf",cat:"ISO - Ankle",name:"Time to Peak Force",unit:"s",bi:true},
  {id:"hip_iso_pf",cat:"ISO - Hip",name:"Peak Force",unit:"N",bi:true},{id:"hip_iso_rpf",cat:"ISO - Hip",name:"Peak Force/BM",unit:"N/kg",bi:true},{id:"hip_iso_f50",cat:"ISO - Hip",name:"Force at 50ms",unit:"N",bi:true},{id:"hip_iso_f100",cat:"ISO - Hip",name:"Force at 100ms",unit:"N",bi:true},{id:"hip_iso_f200",cat:"ISO - Hip",name:"Force at 200ms",unit:"N",bi:true},{id:"hip_iso_imp100",cat:"ISO - Hip",name:"Impulse 100ms",unit:"N s",bi:true},{id:"hip_iso_netpf",cat:"ISO - Hip",name:"Net Peak Force",unit:"N",bi:true},{id:"hip_iso_ttpf",cat:"ISO - Hip",name:"Time to Peak Force",unit:"s",bi:true},
  {id:"calf_iso_pf",cat:"ISO - Calf",name:"Peak Force",unit:"N",bi:true},{id:"calf_iso_rpf",cat:"ISO - Calf",name:"Peak Force/BW",unit:"xBW",bi:true},{id:"calf_iso_f50",cat:"ISO - Calf",name:"Force at 50ms",unit:"N",bi:true},{id:"calf_iso_f100",cat:"ISO - Calf",name:"Force at 100ms",unit:"N",bi:true},{id:"calf_iso_f200",cat:"ISO - Calf",name:"Force at 200ms",unit:"N",bi:true},{id:"calf_iso_imp100",cat:"ISO - Calf",name:"Impulse 100ms",unit:"N s",bi:true},{id:"calf_iso_netpf",cat:"ISO - Calf",name:"Net Peak Force",unit:"N",bi:true},{id:"calf_iso_ttpf",cat:"ISO - Calf",name:"Time to Peak Force",unit:"s",bi:true},
  {id:"single_hop",cat:"Rehab & ROM",name:"Single Hop Test",unit:"cm",bi:true},{id:"triple_hop",cat:"Rehab & ROM",name:"Triple Hop Test",unit:"cm",bi:true},{id:"hip_ir_rom",cat:"Rehab & ROM",name:"Hip IR - ROM",unit:"deg",bi:true},{id:"ktw",cat:"Rehab & ROM",name:"Knee To Wall",unit:"cm",bi:true},{id:"eyes_closed_bal",cat:"Rehab & ROM",name:"Eyes Closed Balance",unit:"s",bi:true},{id:"calf_raise_cap",cat:"Rehab & ROM",name:"Calf Raise Capacity",unit:"reps",bi:true},{id:"tibial_er_rom",cat:"Rehab & ROM",name:"Tibial ER - ROM",unit:"deg",bi:true},{id:"vm_step_down",cat:"Rehab & ROM",name:"VM Step Down",unit:"/3",bi:true},
];

const CAT_COLORS={"CMJ":C.teal,"SL CMJ":"#0EA5E9","DL Hop":C.blue,"SL Hop":"#6366F1","DL Drop Jump":"#A855F7","SL Drop Jump":"#7C3AED","ISO - Knee":C.coral,"ISO - Ankle":"#F97316","ISO - Hip":"#EC4899","ISO - Calf":C.gold,"Rehab & ROM":C.green};

const DEFAULT_QUADRANTS=[
  {id:"q1",title:"Neuromuscular",xMetric:"cmj_pp_bm",yMetric:"cmj_jh",labels:["Reactive","Explosive","Underpowered","Powerful"]},
  {id:"q2",title:"CMJ Strategy",xMetric:"cmj_rsi_mod",yMetric:"cmj_jh",labels:["High but Slow","Fast & High","Slow & Low","Fast but Low"]},
  {id:"q3",title:"Eccentric Profile",xMetric:"cmj_ecc_rfd_bm",yMetric:"cmj_ecc_pf_bm",labels:["Fast but Weak","Strong & Fast","Low Capacity","Strong but Slow"]},
  {id:"q4",title:"Reactive Strength",xMetric:"cmj_jh",yMetric:"cmj_ft_ct",labels:["Slow SSC","Complete","Develop","Fast SSC"]},
  {id:"q5",title:"Knee ISO",xMetric:"knee_iso_pf",yMetric:"knee_iso_f200",labels:["Fast but Weak","Strong & Fast","Low Capacity","Strong but Slow"],avgLR:true},
  {id:"q6",title:"Ankle ISO",xMetric:"ankle_iso_pf",yMetric:"ankle_iso_f200",labels:["Fast but Weak","Strong & Fast","Low Capacity","Strong but Slow"],avgLR:true},
];

// ═══════════════════════════════════════════════════════════════════
// FORCEDECKS CSV PARSER — FIXED DATE HANDLING + FULL SLCMJ MAPPING
// ═══════════════════════════════════════════════════════════════════

// Robust date parser: handles D/M/YYYY, DD/MM/YYYY, DD/M/YYYY etc.
function parseFDDate(r){
  if(!r)return"";
  const p=r.trim().split("/");
  if(p.length===3){
    const d=p[0].padStart(2,"0"),m=p[1].padStart(2,"0"),y=p[2];
    return`${y}-${m}-${d}`;
  }
  return r;
}

function parseAsymVal(r){if(!r||typeof r!=="string")return null;const m=r.trim().match(/^([\d.]+)\s*(L|R)$/);return m?parseFloat(m[1]):parseFloat(r)||null;}

function makeISOMap(p){return{"Peak Vertical Force [N] (L)":`${p}_pf_L`,"Peak Vertical Force [N] (R)":`${p}_pf_R`,"Peak Vertical Force / BM [N/kg] (L)":`${p}_rpf_L`,"Peak Vertical Force / BM [N/kg] (R)":`${p}_rpf_R`,"Peak Vertical Force / BW  (L)":`${p}_rpf_L`,"Peak Vertical Force / BW  (R)":`${p}_rpf_R`,"Peak Vertical Force / BW (L)":`${p}_rpf_L`,"Peak Vertical Force / BW (R)":`${p}_rpf_R`,"Force at 50ms [N] (L)":`${p}_f50_L`,"Force at 50ms [N] (R)":`${p}_f50_R`,"Force at 100ms [N] (L)":`${p}_f100_L`,"Force at 100ms [N] (R)":`${p}_f100_R`,"Force at 200ms [N] (L)":`${p}_f200_L`,"Force at 200ms [N] (R)":`${p}_f200_R`,"Absolute Impulse - 100ms [N s] (L)":`${p}_imp100_L`,"Absolute Impulse - 100ms [N s] (R)":`${p}_imp100_R`,"Peak Vertical Force (Net of BW) [N] (L)":`${p}_netpf_L`,"Peak Vertical Force (Net of BW) [N] (R)":`${p}_netpf_R`,"Start Time to Peak Force [s] (L)":`${p}_ttpf_L`,"Start Time to Peak Force [s] (R)":`${p}_ttpf_R`};}

const FD_MAPS={
  CMJ:{"Jump Height (Imp-Mom) [cm]":"cmj_jh","RSI-modified (Imp-Mom) [m/s]":"cmj_rsi_mod","Contraction Time [ms]":"cmj_ct","Countermovement Depth [cm]":"cmj_cmd","Concentric Peak Force / BM [N/kg]":"cmj_con_pf_bm","Force at Zero Velocity / BM [N/kg]":"cmj_fzv_bm","Concentric Impulse-100ms [N s]":"cmj_con_imp100","Concentric Peak Velocity [m/s]":"cmj_con_pv","Eccentric Peak Force / BM [N/kg]":"cmj_ecc_pf_bm","Eccentric Duration [ms]":"cmj_ecc_dur","Eccentric Deceleration RFD / BM [N/s/kg]":"cmj_ecc_rfd_bm","Eccentric Peak Velocity [m/s]":"cmj_ecc_pv","Flight Time:Contraction Time":"cmj_ft_ct","Peak Power / BM [W/kg]":"cmj_pp_bm","Eccentric Deceleration Impulse / BM [N s/kg]":"cmj_ecc_imp_bm","Eccentric Braking Impulse % (Asym) (%)":"cmj_ecc_brk_asym","Concentric Impulse % (Asym) (%)":"cmj_con_imp_asym","Eccentric Peak Force % (Asym) (%)":"cmj_ecc_pf_asym","Eccentric Deceleration RFD % (Asym) (%)":"cmj_ecc_rfd_asym"},
  // SLCMJ — corrected to match actual ForceDecks column names
  SLCMJ:{"Jump Height (Imp-Mom) [cm] (L)":"slcmj_jh_L","Jump Height (Imp-Mom) [cm] (R)":"slcmj_jh_R","RSI-modified (Imp-Mom) [m/s] (L)":"slcmj_rsi_L","RSI-modified (Imp-Mom) [m/s] (R)":"slcmj_rsi_R","Contraction Time [ms] (L)":"slcmj_ct_L","Contraction Time [ms] (R)":"slcmj_ct_R","Concentric Duration [ms] (L)":"slcmj_con_dur_L","Concentric Duration [ms] (R)":"slcmj_con_dur_R","Eccentric Duration [ms] (L)":"slcmj_ecc_dur_L","Eccentric Duration [ms] (R)":"slcmj_ecc_dur_R","Countermovement Depth [cm] (L)":"slcmj_cmd_L","Countermovement Depth [cm] (R)":"slcmj_cmd_R","Eccentric Peak Force [N] (L)":"slcmj_ecc_pf_L","Eccentric Peak Force [N] (R)":"slcmj_ecc_pf_R","Concentric Peak Force [N] (L)":"slcmj_con_pf_L","Concentric Peak Force [N] (R)":"slcmj_con_pf_R","Eccentric Peak Force / BM [N/kg] (L)":"slcmj_ecc_pf_bm_L","Eccentric Peak Force / BM [N/kg] (R)":"slcmj_ecc_pf_bm_R","Concentric Peak Force / BM [N/kg] (L)":"slcmj_con_pf_bm_L","Concentric Peak Force / BM [N/kg] (R)":"slcmj_con_pf_bm_R","Concentric Impulse [N s] (L)":"slcmj_con_imp_L","Concentric Impulse [N s] (R)":"slcmj_con_imp_R","Eccentric Deceleration Impulse [N s] (L)":"slcmj_ecc_dec_imp_L","Eccentric Deceleration Impulse [N s] (R)":"slcmj_ecc_dec_imp_R","Force at Zero Velocity [N] (L)":"slcmj_fzv_L","Force at Zero Velocity [N] (R)":"slcmj_fzv_R","Eccentric Peak Velocity [m/s] (L)":"slcmj_ecc_pv_L","Eccentric Peak Velocity [m/s] (R)":"slcmj_ecc_pv_R","Concentric Peak Velocity [m/s] (L)":"slcmj_con_pv_L","Concentric Peak Velocity [m/s] (R)":"slcmj_con_pv_R","Eccentric Deceleration RFD [N/s] (L)":"slcmj_brk_rfd_L","Eccentric Deceleration RFD [N/s] (R)":"slcmj_brk_rfd_R","Concentric Time to Peak Force [ms] (L)":"slcmj_con_ttpf_L","Concentric Time to Peak Force [ms] (R)":"slcmj_con_ttpf_R"},
  DLHOP:{"Jump Height (Flight Time) [cm]":"dlhop_jh","Jump Height (Imp-Mom) [cm]":"dlhop_jh","RSI (Flight Time) [m/s]":"dlhop_rsi","RSI-modified (Imp-Mom) [m/s]":"dlhop_rsi","Contact Time [ms]":"dlhop_ct","Ground Contact Time [ms]":"dlhop_ct","Peak Vertical Force [N]":"dlhop_pf","Flight Time:Contraction Time":"dlhop_ft_ct","Flight Time:Contact Time":"dlhop_ft_ct"},
  SLHOP:{"Jump Height (Flight Time) [cm] (L)":"slhop_jh_L","Jump Height (Flight Time) [cm] (R)":"slhop_jh_R","Jump Height (Imp-Mom) [cm] (L)":"slhop_jh_L","Jump Height (Imp-Mom) [cm] (R)":"slhop_jh_R","RSI (Flight Time) [m/s] (L)":"slhop_rsi_L","RSI (Flight Time) [m/s] (R)":"slhop_rsi_R","Contact Time [ms] (L)":"slhop_ct_L","Contact Time [ms] (R)":"slhop_ct_R","Peak Vertical Force [N] (L)":"slhop_pf_L","Peak Vertical Force [N] (R)":"slhop_pf_R"},
  DLDJ:{"Jump Height (Flight Time) [cm]":"dldj_jh","Jump Height (Imp-Mom) [cm]":"dldj_jh","RSI (Flight Time) [m/s]":"dldj_rsi","Contact Time [ms]":"dldj_ct","Peak Landing Force [N]":"dldj_pf","Peak Vertical Force [N]":"dldj_pf","Stiffness [N/m]":"dldj_stiff","Vertical Stiffness [N/m]":"dldj_stiff"},
  SLDJ:{"Jump Height (Flight Time) [cm] (L)":"sldj_jh_L","Jump Height (Flight Time) [cm] (R)":"sldj_jh_R","RSI (Flight Time) [m/s] (L)":"sldj_rsi_L","RSI (Flight Time) [m/s] (R)":"sldj_rsi_R","Contact Time [ms] (L)":"sldj_ct_L","Contact Time [ms] (R)":"sldj_ct_R","Peak Vertical Force [N] (L)":"sldj_pf_L","Peak Vertical Force [N] (R)":"sldj_pf_R"},
  RSKIP:makeISOMap("knee_iso"),RSAKP:makeISOMap("ankle_iso"),RSHIP:makeISOMap("hip_iso"),SLSEICR:makeISOMap("calf_iso"),
};
const FD_LABELS={CMJ:"CMJ",SLCMJ:"SL CMJ",DLHOP:"DL Hop",SLHOP:"SL Hop",DLDJ:"DL Drop Jump",SLDJ:"SL Drop Jump",RSKIP:"Knee ISO",RSAKP:"Ankle ISO",RSHIP:"Hip ISO",SLSEICR:"Calf ISO"};

function parseMultipleCSVs(fileTexts){
  const allEntries=[],testTypes=[],errors=[];
  for(const{text,fileName}of fileTexts){
    const result=Papa.parse(text,{header:true,skipEmptyLines:true});
    if(!result.data?.length){errors.push(`${fileName}: Empty`);continue;}
    const tt=(result.data[0]["Test Type"]||"").trim();
    if(!FD_MAPS[tt]){errors.push(`${fileName}: Unknown type "${tt}"`);continue;}
    testTypes.push(FD_LABELS[tt]||tt);
    const map=FD_MAPS[tt];
    const grouped={};
    for(const row of result.data){
      const name=(row["Name"]||"").trim();
      const date=parseFDDate((row["Date"]||"").trim());
      if(!name||!date)continue;
      const key=`${name}|||${date}`;
      if(!grouped[key])grouped[key]={name,date,row};
    }
    for(const{name,date,row}of Object.values(grouped)){
      const data={};
      for(const[csvCol,appField]of Object.entries(map)){
        let val=null;
        for(const f of result.meta.fields){if(f.trim()===csvCol){val=row[f];break;}}
        if(val==null||val==="")continue;
        val=String(val).trim();
        if(csvCol.includes("(Asym)")){const n=parseAsymVal(val);if(n!==null)data[appField]=n;}
        else{const n=parseFloat(val);if(!isNaN(n))data[appField]=csvCol.toLowerCase().includes("depth")?Math.abs(n):n;}
      }
      if(Object.keys(data).length>0)allEntries.push({name,date,data});
    }
  }
  // Merge by athlete+date
  const merged={};
  for(const{name,date,data}of allEntries){if(!merged[name])merged[name]={};if(!merged[name][date])merged[name][date]={date};Object.assign(merged[name][date],data);}
  const byAthlete={};for(const[name,dates]of Object.entries(merged))byAthlete[name]=Object.values(dates).sort((a,b)=>(a.date||"").localeCompare(b.date||""));
  const metricIds=new Set();for(const ss of Object.values(byAthlete))for(const s of ss)for(const k of Object.keys(s)){if(k==="date"||k==="notes")continue;metricIds.add(k.replace(/_[LR]$/,""));}
  return{byAthlete,athletes:Object.keys(byAthlete),testTypes:[...new Set(testTypes)],errors,metricIds:[...metricIds]};
}

// ─── Utils & Components (same as before) ─────────────────────────
const calcLSI=(l,r)=>{if(!l||!r)return null;return Math.round((Math.min(l,r)/Math.max(l,r))*100);};
const calcAsym=(l,r)=>{if(!l||!r)return null;const h=Math.max(l,r);return h===0?0:Math.round(Math.abs(l-r)/h*1000)/10;};
const getStatus=p=>p===null?"none":p<=10?"normal":p<=15?"monitor":"flag";
const sSt={flag:{bg:C.redBg,c:C.redDark},monitor:{bg:C.amberBg,c:C.amberDark},normal:{bg:C.greenBg,c:C.greenDark}};
const Card=({children,style,...p})=><div style={{background:C.card,borderRadius:14,padding:20,border:`1px solid ${C.border}`,boxShadow:C.shadow,...style}} {...p}>{children}</div>;
const Pill=({status,value})=>{if(!status||status==="none")return null;const s=sSt[status];return<span style={{background:s.bg,color:s.c,padding:"3px 10px",borderRadius:20,fontSize:11,fontWeight:700}}>{status==="flag"?"Flag":status==="monitor"?"Monitor":"Normal"}{value!=null?` ${value}%`:""}</span>;};
const LSIPill=({lsi,side})=>{if(lsi===null)return null;const ok=lsi>=90,mid=lsi>=85;return<span style={{background:ok?C.greenBg:mid?C.amberBg:C.redBg,color:ok?C.greenDark:mid?C.amberDark:C.redDark,padding:"3px 10px",borderRadius:20,fontSize:11,fontWeight:700}}>LSI: {lsi}%{side?` (${side} lower)`:""}</span>;};
const Toggle=({on,onToggle,size=20})=>(<div onClick={e=>{e.stopPropagation();onToggle();}} style={{width:size*2,height:size,borderRadius:size,background:on?C.teal:C.border,cursor:"pointer",position:"relative",transition:"background 0.2s",flexShrink:0}}><div style={{width:size-4,height:size-4,borderRadius:"50%",background:"#fff",position:"absolute",top:2,left:on?size+2:2,transition:"left 0.2s",boxShadow:"0 1px 3px rgba(0,0,0,0.2)"}}/></div>);
const Btn=({children,primary,danger,small,accent,style,...p})=>(<button style={{padding:small?"6px 14px":"10px 20px",borderRadius:10,border:primary||danger||accent?"none":`1px solid ${C.border}`,background:primary?C.carltonNavy:danger?C.redBg:accent?C.teal:"#fff",color:primary||accent?"#fff":danger?C.redDark:C.text,fontWeight:600,fontSize:small?12:13,cursor:"pointer",...style}} {...p}>{children}</button>);
const SectionHead=({title,color,count})=>(<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14,marginTop:28}}><div style={{width:10,height:10,borderRadius:"50%",background:color||C.teal}}/><h3 style={{margin:0,fontSize:17,fontWeight:700,color:C.carltonNavy}}>{title}</h3>{count!=null&&<span style={{fontSize:11,color:C.textLight,background:C.bg,padding:"2px 8px",borderRadius:10}}>{count}</span>}</div>);
function Modal({title,onClose,children,wide}){return(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",display:"flex",justifyContent:"center",alignItems:"flex-start",zIndex:200,backdropFilter:"blur(2px)",overflowY:"auto",padding:"40px 16px"}} onClick={onClose}><Card style={{width:wide?620:380,padding:28,maxWidth:"100%"}} onClick={e=>e.stopPropagation()}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><span style={{fontWeight:700,fontSize:18,color:C.carltonNavy}}>{title}</span><button onClick={onClose} style={{background:"none",border:"none",fontSize:20,cursor:"pointer",color:C.textLight,padding:4}}>✕</button></div>{children}</Card></div>);}

function CSVImporter({onImport,onClose,existingAthletes}){
  const[dragOver,setDragOver]=useState(false);const[parsed,setParsed]=useState(null);const[errors,setErrors]=useState([]);const[sel,setSel]=useState({});const fileRef=useRef();
  const handleFiles=files=>{if(!files?.length)return;setErrors([]);const readers=[];for(const f of files)readers.push(new Promise(res=>{const r=new FileReader();r.onload=e=>res({text:e.target.result,fileName:f.name});r.readAsText(f);}));Promise.all(readers).then(results=>{const res=parseMultipleCSVs(results);if(res.errors.length&&!res.athletes.length){setErrors(res.errors);return;}if(res.errors.length)setErrors(res.errors);setParsed(res);const s={};res.athletes.forEach(a=>{s[a]=true;});setSel(s);});};
  return(<Modal title="Import ForceDecks CSVs" onClose={onClose} wide>{!parsed?(<><div onDrop={e=>{e.preventDefault();setDragOver(false);handleFiles(e.dataTransfer?.files);}} onDragOver={e=>{e.preventDefault();setDragOver(true);}} onDragLeave={()=>setDragOver(false)} onClick={()=>fileRef.current?.click()} style={{border:`2px dashed ${dragOver?C.teal:C.border}`,borderRadius:12,padding:40,textAlign:"center",cursor:"pointer",background:dragOver?"#F0FDFA":C.bg}}><div style={{fontSize:36,marginBottom:8}}>📄</div><div style={{fontWeight:600,color:C.text,marginBottom:4}}>Drop multiple CSVs here</div><div style={{fontSize:11,color:C.textLight}}>Same-day data merges automatically</div><input ref={fileRef} type="file" accept=".csv" multiple style={{display:"none"}} onChange={e=>handleFiles(e.target.files)}/></div>{errors.length>0&&<div style={{marginTop:12,padding:12,borderRadius:8,background:C.redBg,color:C.redDark,fontSize:12}}>{errors.map((e,i)=><div key={i}>{e}</div>)}</div>}</>):(<>
    <Card style={{background:"#F0FDFA",borderColor:C.teal,marginBottom:16}}><div style={{fontWeight:700,color:C.carltonNavy}}>{parsed.testTypes.join(" + ")}</div><div style={{fontSize:12,color:C.textMid}}>{parsed.athletes.length} athletes • {parsed.metricIds.length} metrics</div></Card>
    {errors.length>0&&<div style={{marginBottom:12,padding:10,borderRadius:8,background:C.amberBg,color:C.amberDark,fontSize:11}}>{errors.map((e,i)=><div key={i}>⚠ {e}</div>)}</div>}
    {parsed.athletes.map(n=>{const exists=existingAthletes.includes(n);const sessions=parsed.byAthlete[n];return(<div key={n} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"10px 0",borderBottom:`1px solid ${C.borderLight}`}}><div><span style={{fontWeight:600}}>{n}</span>{exists&&<span style={{fontSize:10,background:C.amberBg,color:C.amberDark,padding:"1px 6px",borderRadius:4,marginLeft:6}}>Merge</span>}<div style={{fontSize:11,color:C.textLight}}>{sessions.length} session{sessions.length>1?"s":""}</div></div><Toggle on={!!sel[n]} onToggle={()=>setSel(p=>({...p,[n]:!p[n]}))}/></div>);})}
    <div style={{display:"flex",gap:8,marginTop:20}}><Btn style={{flex:1}} onClick={()=>setParsed(null)}>← Back</Btn><Btn accent style={{flex:2}} onClick={()=>{const a={};for(const[n,ss]of Object.entries(parsed.byAthlete)){if(sel[n])a[n]=ss;}onImport(a,parsed.testTypes,parsed.metricIds);}}>Import</Btn></div></>)}</Modal>);
}

function BilateralCard({m,data,pb,prev}){const l=data?.[`${m.id}_L`],r=data?.[`${m.id}_R`];if(l==null&&r==null)return null;const lsi=calcLSI(l,r),lo=l<r?"L":l>r?"R":null;
  const S=({label,val,isLo,pbV,pv})=>{const d=val!=null&&pv!=null?val-pv:null;return(<div style={{flex:1,background:isLo?"#FEF2F2":"#F0FDF4",borderRadius:10,padding:14,border:`1px solid ${isLo?"#FECACA":"#BBF7D0"}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}><span style={{fontSize:11,color:C.textLight,fontWeight:700,letterSpacing:.5}}>{label}</span>{isLo&&<span style={{fontSize:10,background:C.coral,color:"#fff",padding:"1px 8px",borderRadius:6,fontWeight:600}}>Lower</span>}</div><div style={{fontSize:26,fontWeight:800,color:C.text}}>{val??'—'} <span style={{fontSize:12,fontWeight:400,color:C.textLight}}>{m.unit}</span></div><div style={{display:"flex",gap:8,alignItems:"center",marginTop:4}}>{pbV!=null&&<span style={{fontSize:10,color:C.textLight}}>PB: {pbV}</span>}{d!=null&&d!==0&&<span style={{fontSize:10,fontWeight:600,color:d>0?C.greenDark:C.redDark}}>{d>0?"▲":"▼"} {Math.abs(Math.round(d*10)/10)}</span>}</div></div>);};
  return(<Card style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><span style={{fontWeight:600,fontSize:14,color:C.text}}>{m.cat} — {m.name}</span><LSIPill lsi={lsi} side={lo}/></div><div style={{display:"flex",gap:10}}><S label="LEFT" val={l} isLo={lo==="L"} pbV={pb?.[`${m.id}_L`]} pv={prev?.[`${m.id}_L`]}/><S label="RIGHT" val={r} isLo={lo==="R"} pbV={pb?.[`${m.id}_R`]} pv={prev?.[`${m.id}_R`]}/></div></Card>);}

function UnilateralCard({m,data,pb,prev}){const v=data?.[m.id];if(v==null)return null;const d=v!=null&&prev?.[m.id]!=null?v-prev[m.id]:null;
  return(<Card style={{marginBottom:10}}><span style={{fontWeight:600,fontSize:14,color:C.text}}>{m.cat} — {m.name}</span><div style={{fontSize:30,fontWeight:800,color:C.text,marginTop:6}}>{v} <span style={{fontSize:12,fontWeight:400,color:C.textLight}}>{m.unit}</span></div><div style={{display:"flex",gap:8,alignItems:"center",marginTop:4}}>{pb?.[m.id]!=null&&<span style={{fontSize:10,color:C.textLight}}>PB: {pb[m.id]}</span>}{d!=null&&d!==0&&<span style={{fontSize:10,fontWeight:600,color:d>0?C.greenDark:C.redDark}}>{d>0?"▲":"▼"} {Math.abs(Math.round(d*10)/10)}</span>}</div></Card>);}

function TeamQuadrantChart({qConfig,allAthletes,currentAthlete,metricMap,onEdit,onDelete}){
  const{title,xMetric,yMetric,labels,avgLR}=qConfig;
  const xM=metricMap[xMetric],yM=metricMap[yMetric];
  const xLabel=xM?`${xM.name}`:xMetric;const yLabel=yM?`${yM.name}`:yMetric;
  const getVal=(s,mid)=>{if(avgLR){const l=s[`${mid}_L`],r=s[`${mid}_R`];if(l!=null&&r!=null)return(l+r)/2;return l||r||null;}return s[mid]??null;};
  const points=[];for(const[name,sessions]of Object.entries(allAthletes)){if(!sessions?.length)continue;const s=sessions[sessions.length-1];const x=getVal(s,xMetric),y=getVal(s,yMetric);if(x==null||y==null)continue;points.push({x,y,name,isCurrent:name===currentAthlete});}
  if(points.length===0)return null;
  const xAvg=points.reduce((s,p)=>s+p.x,0)/points.length,yAvg=points.reduce((s,p)=>s+p.y,0)/points.length;
  const cur=points.find(p=>p.isCurrent);const qi=cur?(cur.x>=xAvg&&cur.y>=yAvg?1:cur.x<xAvg&&cur.y>=yAvg?0:cur.x>=xAvg?3:2):null;
  const qC=[C.redBg,C.greenBg,C.redBg,C.blueBg],qT=[C.coral,C.greenDark,C.redDark,C.blue];
  return(<Card style={{flex:1,minWidth:300,marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:2}}><div><div style={{fontWeight:700,fontSize:15,color:C.carltonNavy}}>{title}</div><div style={{fontSize:10,color:C.textLight}}>{xLabel} vs {yLabel}</div></div><div style={{display:"flex",gap:4}}><span style={{fontSize:10,color:C.textLight,background:C.bg,padding:"2px 8px",borderRadius:8}}>{points.length}</span><button onClick={onEdit} style={{background:"none",border:"none",cursor:"pointer",fontSize:12,color:C.textLight,padding:"2px 4px"}}>✏️</button><button onClick={onDelete} style={{background:"none",border:"none",cursor:"pointer",fontSize:12,color:C.textLight,padding:"2px 4px"}}>✕</button></div></div>
    <div style={{position:"relative"}}>{labels&&<div style={{position:"absolute",top:8,left:45,right:8,bottom:28,zIndex:0,pointerEvents:"none"}}><span style={{position:"absolute",top:0,left:0,fontSize:8,color:qT[0],fontWeight:700,background:qC[0],padding:"1px 5px",borderRadius:4}}>{labels[0]}</span><span style={{position:"absolute",top:0,right:0,fontSize:8,color:qT[1],fontWeight:700,background:qC[1],padding:"1px 5px",borderRadius:4}}>{labels[1]}</span><span style={{position:"absolute",bottom:0,left:0,fontSize:8,color:qT[2],fontWeight:700,background:qC[2],padding:"1px 5px",borderRadius:4}}>{labels[2]}</span><span style={{position:"absolute",bottom:0,right:0,fontSize:8,color:qT[3],fontWeight:700,background:qC[3],padding:"1px 5px",borderRadius:4}}>{labels[3]}</span></div>}<ResponsiveContainer width="100%" height={220}><ScatterChart margin={{top:16,right:8,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={C.borderLight}/><XAxis type="number" dataKey="x" domain={['auto','auto']} tick={{fontSize:9}} stroke={C.border}/><YAxis type="number" dataKey="y" domain={['auto','auto']} tick={{fontSize:9}} stroke={C.border}/><ReferenceLine x={xAvg} stroke={C.carltonSilver} strokeDasharray="6 4" strokeWidth={1.5}/><ReferenceLine y={yAvg} stroke={C.carltonSilver} strokeDasharray="6 4" strokeWidth={1.5}/><Tooltip content={({payload})=>{if(!payload?.[0])return null;const d=payload[0].payload;return<div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:8,padding:8,fontSize:11}}><div style={{fontWeight:700,color:d.isCurrent?C.teal:C.text}}>{d.name}{d.isCurrent?" ★":""}</div><div>{xLabel}: {Math.round(d.x*100)/100}</div><div>{yLabel}: {Math.round(d.y*100)/100}</div></div>;}}/><Scatter data={points}>{points.map((p,i)=><Cell key={i} fill={p.isCurrent?C.teal:C.carltonSilver} r={p.isCurrent?8:4} opacity={p.isCurrent?1:0.5} stroke={p.isCurrent?C.carltonNavy:"none"} strokeWidth={p.isCurrent?2:0}/>)}</Scatter></ScatterChart></ResponsiveContainer></div>
    {cur&&labels&&qi!==null&&<div style={{marginTop:6,padding:"6px 10px",borderRadius:8,background:qC[qi],fontSize:12,fontWeight:700,color:qT[qi]}}>{currentAthlete}: {labels[qi]} ✓</div>}</Card>);}

function QuadrantEditor({qConfig,metrics,onSave,onClose}){const[title,setTitle]=useState(qConfig?.title||"");const[xMetric,setXMetric]=useState(qConfig?.xMetric||"");const[yMetric,setYMetric]=useState(qConfig?.yMetric||"");const[avgLR,setAvgLR]=useState(qConfig?.avgLR||false);const[labels,setLabels]=useState(qConfig?.labels||["Top-Left","Top-Right","Bottom-Left","Bottom-Right"]);const setL=(i,v)=>{const n=[...labels];n[i]=v;setLabels(n);};const opts=metrics.map(m=>({id:m.id,label:`${m.cat} — ${m.name} (${m.unit})`}));
  const Sel=({value,onChange,label:lbl})=>(<div style={{marginBottom:14}}><label style={{fontSize:12,color:C.textLight,fontWeight:600,display:"block",marginBottom:4}}>{lbl}</label><select value={value} onChange={e=>onChange(e.target.value)} style={{width:"100%",padding:"10px 12px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:13,boxSizing:"border-box",background:"#fff"}}><option value="">Select metric...</option>{opts.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></div>);
  return(<Modal title={qConfig?"Edit Quadrant":"Add Quadrant"} onClose={onClose} wide><div style={{marginBottom:14}}><label style={{fontSize:12,color:C.textLight,fontWeight:600,display:"block",marginBottom:4}}>Title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Neuromuscular" style={{width:"100%",padding:"10px 12px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:13,boxSizing:"border-box"}}/></div><Sel value={xMetric} onChange={setXMetric} label="X-Axis Metric"/><Sel value={yMetric} onChange={setYMetric} label="Y-Axis Metric"/><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:14}}><Toggle on={avgLR} onToggle={()=>setAvgLR(!avgLR)} size={18}/><span style={{fontSize:12,color:C.text}}>Average L+R for bilateral</span></div><div style={{fontWeight:600,fontSize:12,color:C.textLight,marginBottom:8}}>Quadrant Labels</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:14}}><input value={labels[0]} onChange={e=>setL(0,e.target.value)} placeholder="Top-Left" style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:12}}/><input value={labels[1]} onChange={e=>setL(1,e.target.value)} placeholder="Top-Right" style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:12}}/><input value={labels[2]} onChange={e=>setL(2,e.target.value)} placeholder="Bottom-Left" style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:12}}/><input value={labels[3]} onChange={e=>setL(3,e.target.value)} placeholder="Bottom-Right" style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:12}}/></div><div style={{display:"flex",gap:8}}><Btn style={{flex:1}} onClick={onClose}>Cancel</Btn><Btn primary style={{flex:1}} onClick={()=>{if(!title||!xMetric||!yMetric)return;onSave({id:qConfig?.id||"q_"+Date.now(),title,xMetric,yMetric,avgLR,labels});onClose();}}>Save</Btn></div></Modal>);}

function AsymRow({name,l,r}){const a=calcAsym(l,r);if(a===null)return null;const s=getStatus(a),total=l+r,lp=total>0?(l/total)*100:50;return(<div style={{display:"flex",alignItems:"center",padding:"7px 0",borderBottom:`1px solid ${C.borderLight}`,gap:6}}><div style={{flex:2.5,fontSize:11,color:C.text,fontWeight:500,minWidth:160}}>{name}</div><div style={{flex:2,display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:9,color:C.textLight,width:48,textAlign:"right",fontVariantNumeric:"tabular-nums"}}>L: {l}</span><div style={{flex:1,height:7,borderRadius:4,background:C.borderLight,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:0,top:0,bottom:0,width:`${lp}%`,background:s==="flag"?C.red:s==="monitor"?C.amber:C.green,borderRadius:4}}/></div><span style={{fontSize:9,color:C.textLight,width:48,fontVariantNumeric:"tabular-nums"}}>R: {r}</span></div><Pill status={s} value={a}/></div>);}

function MetricConfig({metrics,visibleMetrics,onUpdateVisible,onDeleteMetric,allDataMetrics}){const[search,setSearch]=useState("");const grouped={};for(const m of metrics){if(search&&!m.name.toLowerCase().includes(search.toLowerCase())&&!m.cat.toLowerCase().includes(search.toLowerCase()))continue;if(!grouped[m.cat])grouped[m.cat]=[];grouped[m.cat].push({...m,hasData:allDataMetrics.has(m.id)});}const toggleM=id=>{const s=new Set(visibleMetrics);s.has(id)?s.delete(id):s.add(id);onUpdateVisible([...s]);};const toggleC=cat=>{const ms=metrics.filter(m=>m.cat===cat);const allOn=ms.every(m=>visibleMetrics.includes(m.id));const s=new Set(visibleMetrics);ms.forEach(m=>allOn?s.delete(m.id):s.add(m.id));onUpdateVisible([...s]);};
  return(<div><div style={{position:"sticky",top:92,zIndex:80,background:C.bg,paddingBottom:12}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..." style={{width:"100%",padding:"10px 14px",borderRadius:10,border:`1px solid ${C.border}`,fontSize:13,boxSizing:"border-box",background:"#fff"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:8,flexWrap:"wrap",gap:8}}><span style={{fontSize:12,color:C.textLight}}>{visibleMetrics.length} shown • {allDataMetrics.size} with data</span><div style={{display:"flex",gap:6}}><Btn small onClick={()=>onUpdateVisible([...allDataMetrics])}>All with Data</Btn><Btn small onClick={()=>onUpdateVisible([])}>Hide All</Btn></div></div></div>{Object.entries(grouped).map(([cat,ms])=>{const allOn=ms.every(m=>visibleMetrics.includes(m.id));return(<Card key={cat} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10,cursor:"pointer"}} onClick={()=>toggleC(cat)}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:10,height:10,borderRadius:"50%",background:CAT_COLORS[cat]||C.purple}}/><span style={{fontWeight:700,fontSize:14,color:C.carltonNavy}}>{cat}</span><span style={{fontSize:11,color:C.textLight}}>{ms.filter(m=>visibleMetrics.includes(m.id)).length}/{ms.length}</span></div><Toggle on={allOn} onToggle={()=>toggleC(cat)}/></div>{ms.map(m=>(<div key={m.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"6px 0 6px 18px",borderTop:`1px solid ${C.borderLight}`}}><div><span style={{fontSize:12,color:m.hasData?C.text:C.textLight}}>{m.name}</span><span style={{fontSize:10,color:C.textLight,marginLeft:6}}>{m.unit}{m.bi?" • L/R":""}</span>{!m.hasData&&<span style={{fontSize:9,color:C.textLight,marginLeft:4}}>(no data)</span>}</div><div style={{display:"flex",gap:6,alignItems:"center"}}><Toggle on={visibleMetrics.includes(m.id)} onToggle={()=>toggleM(m.id)} size={18}/><button onClick={e=>{e.stopPropagation();if(confirm(`Delete "${m.cat} — ${m.name}"?`))onDeleteMetric(m.id);}} style={{background:"none",border:"none",cursor:"pointer",color:C.textLight,fontSize:13,padding:"2px 4px"}}>✕</button></div></div>))}</Card>);})}</div>);}

function InputForm({metrics,visibleMetrics,onSave,existingData}){const active=metrics.filter(m=>visibleMetrics.includes(m.id));const grouped={};active.forEach(m=>{if(!grouped[m.cat])grouped[m.cat]=[];grouped[m.cat].push(m);});const[form,setForm]=useState(existingData||{date:new Date().toISOString().split("T")[0]});const[notes,setNotes]=useState(existingData?.notes||"");const set=(k,v)=>setForm(p=>({...p,[k]:v===""?undefined:isNaN(parseFloat(v))?v:parseFloat(v)}));
  return(<div><Card style={{marginBottom:12}}><div style={{fontWeight:700,fontSize:14,color:C.carltonNavy,marginBottom:8}}>Date</div><input type="date" value={form.date||""} onChange={e=>set("date",e.target.value)} style={{padding:"8px 12px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:14,width:"100%",boxSizing:"border-box"}}/></Card>{Object.entries(grouped).map(([cat,ms])=>(<Card key={cat} style={{marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><div style={{width:8,height:8,borderRadius:"50%",background:CAT_COLORS[cat]||C.purple}}/><span style={{fontWeight:700,fontSize:14,color:C.carltonNavy}}>{cat}</span></div>{ms.map(m=>(<div key={m.id} style={{marginBottom:14}}><div style={{fontSize:12,fontWeight:600,color:C.text,marginBottom:4}}>{m.name} <span style={{color:C.textLight,fontWeight:400}}>({m.unit})</span></div>{m.bi?(<div style={{display:"flex",gap:8}}><input type="number" step="any" placeholder="Left" value={form[`${m.id}_L`]??""} onChange={e=>set(`${m.id}_L`,e.target.value)} style={{flex:1,padding:"8px 10px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:13}}/><input type="number" step="any" placeholder="Right" value={form[`${m.id}_R`]??""} onChange={e=>set(`${m.id}_R`,e.target.value)} style={{flex:1,padding:"8px 10px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:13}}/></div>):(<input type="number" step="any" placeholder="Value" value={form[m.id]??""} onChange={e=>set(m.id,e.target.value)} style={{width:"100%",padding:"8px 10px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:13,boxSizing:"border-box"}}/>)}</div>))}</Card>))}<Card style={{marginBottom:14}}><div style={{fontWeight:700,fontSize:14,color:C.carltonNavy,marginBottom:8}}>Notes</div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Key takeaways..." style={{width:"100%",minHeight:80,padding:10,borderRadius:8,border:`1px solid ${C.border}`,fontSize:12,resize:"vertical",boxSizing:"border-box",fontFamily:"inherit"}}/></Card><Btn primary style={{width:"100%",padding:"14px 0",fontSize:15}} onClick={()=>onSave({...form,notes})}>Save Session</Btn></div>);}

// ═══════════════════ MAIN APP ═══════════════════
export default function App(){
  const[view,setView]=useState("dashboard");const[athletes,setAthletes]=useState({});const[cur,setCur]=useState("");const[metrics,setMetrics]=useState(DEFAULT_METRICS);const[visibleMetrics,setVisibleMetrics]=useState(["cmj_jh","cmj_rsi_mod","cmj_ct","cmj_cmd","cmj_con_pf_bm","cmj_ecc_pf_bm","cmj_ecc_rfd_bm","cmj_ft_ct","cmj_pp_bm","slcmj_jh","slcmj_rsi","slcmj_ecc_pf","slcmj_con_pf","slcmj_brk_rfd","knee_iso_pf","knee_iso_f100","knee_iso_f200","ankle_iso_pf","ankle_iso_f100","ankle_iso_f200","calf_iso_pf","calf_iso_f100","calf_iso_f200"]);
  const[quadrants,setQuadrants]=useState(DEFAULT_QUADRANTS);const[showAdd,setShowAdd]=useState(false);const[showImport,setShowImport]=useState(false);const[newName,setNewName]=useState("");const[loading,setLoading]=useState(true);const[editIdx,setEditIdx]=useState(null);const[toast,setToast]=useState(null);const[editingQuad,setEditingQuad]=useState(null);
  const metricMap=useMemo(()=>{const m={};metrics.forEach(x=>{m[x.id]=x;});return m;},[metrics]);

  useEffect(()=>{(async()=>{try{const r=await storage.get("carlton-recon-v8");if(r?.value){const d=JSON.parse(r.value);setAthletes(d.a||{});setCur(d.c||"");if(d.m?.length)setMetrics(d.m);if(d.v?.length)setVisibleMetrics(d.v);if(d.q?.length)setQuadrants(d.q);}}catch(e){}setLoading(false);})();},[]);
  const persist=useCallback(async(a,c,m,v,q)=>{try{await storage.set("carlton-recon-v8",JSON.stringify({a,c,m,v,q}));}catch(e){}},[]);
  const sv=(a=athletes,c=cur,m=metrics,v=visibleMetrics,q=quadrants)=>persist(a,c,m,v,q);
  const updateVisible=v=>{setVisibleMetrics(v);sv(athletes,cur,metrics,v,quadrants);};
  const deleteMetric=id=>{const nm=metrics.filter(m=>m.id!==id);const nv=visibleMetrics.filter(v=>v!==id);setMetrics(nm);setVisibleMetrics(nv);sv(athletes,cur,nm,nv,quadrants);};
  const addAthlete=()=>{if(!newName.trim())return;const n=newName.trim(),u={...athletes,[n]:athletes[n]||[]};setAthletes(u);setCur(n);setNewName("");setShowAdd(false);sv(u,n,metrics,visibleMetrics,quadrants);};
  const removeAthlete=()=>{const u={...athletes};delete u[cur];const next=Object.keys(u)[0]||"";setAthletes(u);setCur(next);sv(u,next,metrics,visibleMetrics,quadrants);};
  const saveSession=data=>{const ss=[...(athletes[cur]||[])];if(editIdx!==null)ss[editIdx]=data;else ss.push(data);ss.sort((a,b)=>(a.date||"").localeCompare(b.date||""));const u={...athletes,[cur]:ss};setAthletes(u);sv(u,cur,metrics,visibleMetrics,quadrants);setView("dashboard");setEditIdx(null);};
  const delSession=i=>{const ss=[...(athletes[cur]||[])];ss.splice(i,1);const u={...athletes,[cur]:ss};setAthletes(u);sv(u,cur,metrics,visibleMetrics,quadrants);};
  const saveQuadrant=q=>{const nq=quadrants.find(x=>x.id===q.id)?quadrants.map(x=>x.id===q.id?q:x):[...quadrants,q];setQuadrants(nq);sv(athletes,cur,metrics,visibleMetrics,nq);};
  const deleteQuadrant=id=>{if(!confirm("Delete this quadrant?"))return;const nq=quadrants.filter(q=>q.id!==id);setQuadrants(nq);sv(athletes,cur,metrics,visibleMetrics,nq);};
  const handleCSVImport=(imported,testTypes,metricIds)=>{const updated={...athletes};for(const[name,newSess]of Object.entries(imported)){const existing=updated[name]||[];const byDate={};existing.forEach(s=>{byDate[s.date]={...s};});for(const s of newSess){if(byDate[s.date])Object.assign(byDate[s.date],s);else byDate[s.date]=s;}updated[name]=Object.values(byDate).sort((a,b)=>(a.date||"").localeCompare(b.date||""));}const first=Object.keys(imported)[0]||cur;setAthletes(updated);if(!cur&&first)setCur(first);const nv=new Set(visibleMetrics);metricIds.forEach(id=>nv.add(id));setVisibleMetrics([...nv]);sv(updated,cur||first,metrics,[...nv],quadrants);setShowImport(false);setToast(`✅ ${testTypes.join(" + ")} — ${Object.keys(imported).length} athletes imported`);setTimeout(()=>setToast(null),4000);};

  const sessions=athletes[cur]||[],latest=sessions[sessions.length-1]||{},prev=sessions.length>=2?sessions[sessions.length-2]:null;
  const pbs=useMemo(()=>{const pb={};for(const s of sessions)for(const[k,v]of Object.entries(s)){if(k==="date"||k==="notes")continue;const n=parseFloat(v);if(!isNaN(n)&&(pb[k]===undefined||n>pb[k]))pb[k]=n;}return pb;},[sessions]);
  const allDataMetrics=useMemo(()=>{const s=new Set();for(const sess of sessions)for(const k of Object.keys(sess)){if(k==="date"||k==="notes")continue;s.add(k.replace(/_[LR]$/,""));}return s;},[sessions]);
  const displayMetrics=useMemo(()=>{const grouped={};for(const id of visibleMetrics){const m=metricMap[id];if(!m)continue;const hasData=m.bi?(latest[`${id}_L`]!=null||latest[`${id}_R`]!=null):latest[id]!=null;if(!hasData)continue;if(!grouped[m.cat])grouped[m.cat]=[];grouped[m.cat].push(m);}return grouped;},[visibleMetrics,latest,metricMap]);
  const asymmetries=useMemo(()=>{const list=[];for(const id of visibleMetrics){const m=metricMap[id];if(!m||!m.bi)continue;const l=latest[`${id}_L`],r=latest[`${id}_R`];if(l!=null&&r!=null)list.push({name:`${m.cat} — ${m.name}`,l,r,asym:calcAsym(l,r),status:getStatus(calcAsym(l,r))});}list.sort((a,b)=>b.asym-a.asym);return list;},[latest,visibleMetrics,metricMap]);

  if(loading)return<div style={{display:"flex",justifyContent:"center",alignItems:"center",height:"100vh",fontFamily:"system-ui"}}><div style={{fontSize:16,color:C.carltonNavy,fontWeight:600}}>Loading...</div></div>;

  return(<div style={{fontFamily:"system-ui,-apple-system,sans-serif",background:C.bg,minHeight:"100vh",color:C.text}}>
    <div style={{background:`linear-gradient(135deg,${C.carltonNavy} 0%,#142338 100%)`,padding:"14px 20px",display:"flex",justifyContent:"space-between",alignItems:"center",position:"sticky",top:0,zIndex:100,boxShadow:"0 2px 10px rgba(0,0,0,0.2)"}}><div><div style={{color:"#fff",fontSize:15,fontWeight:800,letterSpacing:1.2}}>CARLTON AFLW</div><div style={{color:C.carltonSilver,fontSize:10,letterSpacing:2.5,marginTop:1}}>PERFORMANCE RECONDITIONING</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}>{Object.keys(athletes).length>0&&<select value={cur} onChange={e=>{setCur(e.target.value);sv(athletes,e.target.value,metrics,visibleMetrics,quadrants);}} style={{padding:"6px 10px",borderRadius:8,border:"none",background:"rgba(255,255,255,0.1)",color:"#fff",fontSize:12,cursor:"pointer"}}>{Object.keys(athletes).sort().map(a=><option key={a} value={a} style={{color:"#000"}}>{a}</option>)}</select>}<Btn small style={{background:"rgba(255,255,255,0.1)",border:"1px solid rgba(255,255,255,0.2)",color:"#fff"}} onClick={()=>setShowAdd(true)}>+</Btn><Btn small style={{background:C.teal,border:"none",color:"#fff"}} onClick={()=>setShowImport(true)}>📄</Btn></div></div>
    {toast&&<div style={{position:"fixed",top:70,left:"50%",transform:"translateX(-50%)",background:C.greenBg,color:C.greenDark,padding:"10px 20px",borderRadius:10,fontWeight:600,fontSize:13,zIndex:300,boxShadow:"0 4px 12px rgba(0,0,0,0.15)",border:`1px solid ${C.green}`,whiteSpace:"nowrap"}}>{toast}</div>}
    {showAdd&&<Modal title="Add Athlete" onClose={()=>{setShowAdd(false);setNewName("");}}><input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addAthlete()} placeholder="Athlete name" style={{width:"100%",padding:"10px 14px",borderRadius:10,border:`1px solid ${C.border}`,fontSize:14,boxSizing:"border-box",marginBottom:14}}/><div style={{display:"flex",gap:8}}><Btn style={{flex:1}} onClick={()=>{setShowAdd(false);setNewName("");}}>Cancel</Btn><Btn primary style={{flex:1}} onClick={addAthlete}>Add</Btn></div></Modal>}
    {showImport&&<CSVImporter onImport={handleCSVImport} onClose={()=>setShowImport(false)} existingAthletes={Object.keys(athletes)}/>}
    {editingQuad!==null&&<QuadrantEditor qConfig={editingQuad==="new"?null:editingQuad} metrics={metrics} onSave={saveQuadrant} onClose={()=>setEditingQuad(null)}/>}

    {!cur?(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",height:"70vh",gap:16}}><div style={{width:80,height:80,borderRadius:20,background:C.carltonNavy,display:"flex",alignItems:"center",justifyContent:"center",color:C.carltonSilver,fontWeight:800,fontSize:14,textAlign:"center",lineHeight:1.2,padding:8}}>CARLTON<br/>AFLW</div><div style={{fontSize:18,fontWeight:700,color:C.carltonNavy}}>Performance Reconditioning Hub</div><div style={{display:"flex",gap:8}}><Btn primary onClick={()=>setShowAdd(true)}>+ Athlete</Btn><Btn accent onClick={()=>setShowImport(true)}>📄 Import</Btn></div></div>):(
    <><div style={{display:"flex",gap:0,background:"#fff",borderBottom:`1px solid ${C.border}`,position:"sticky",top:56,zIndex:90,overflowX:"auto"}}>{[{key:"dashboard",label:"📊 Dashboard"},{key:"input",label:"➕ Manual"},{key:"metrics",label:"⚙️ Metrics"},{key:"history",label:"📋 History"}].map(t=>(<button key={t.key} onClick={()=>{setView(t.key);setEditIdx(null);}} style={{padding:"12px 18px",border:"none",background:"transparent",cursor:"pointer",fontSize:13,fontWeight:600,color:view===t.key?C.carltonNavy:C.textLight,borderBottom:view===t.key?`3px solid ${C.teal}`:"3px solid transparent",whiteSpace:"nowrap"}}>{t.label}</button>))}</div>
    <div style={{maxWidth:820,margin:"0 auto",padding:"20px 16px",paddingBottom:60}}>
      {view==="dashboard"&&(<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24,flexWrap:"wrap",gap:12}}><div style={{display:"flex",alignItems:"center",gap:14}}><div style={{width:52,height:52,borderRadius:14,background:`linear-gradient(135deg,${C.carltonNavy},#1a3050)`,display:"flex",alignItems:"center",justifyContent:"center",color:C.carltonSilver,fontWeight:800,fontSize:17}}>{cur.split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase()}</div><div><div style={{fontSize:22,fontWeight:800,color:C.carltonNavy}}>{cur}</div><div style={{fontSize:12,color:C.textLight}}>{latest.date?`Latest: ${latest.date} • ${sessions.length} sessions`:"No sessions"} • Squad: {Object.keys(athletes).length}</div></div></div><Btn small danger onClick={()=>{if(confirm(`Delete ${cur}?`))removeAthlete();}}>Delete</Btn></div>
        {sessions.length===0?(<Card style={{textAlign:"center",padding:48}}><div style={{fontSize:44,marginBottom:12,opacity:.4}}>📊</div><div style={{fontSize:15,fontWeight:600,color:C.carltonNavy,marginBottom:20}}>No data yet</div><div style={{display:"flex",gap:8,justifyContent:"center"}}><Btn accent onClick={()=>setShowImport(true)}>📄 Import</Btn><Btn primary onClick={()=>setView("input")}>+ Manual</Btn></div></Card>):(<>
          {latest.notes&&<Card style={{marginBottom:20,borderLeft:`4px solid ${C.teal}`,background:"#F0FDFA"}}><div style={{fontWeight:700,fontSize:15,color:C.carltonNavy,marginBottom:6}}>Key Takeaways</div><div style={{fontSize:13,color:C.text,lineHeight:1.7,whiteSpace:"pre-wrap"}}>{latest.notes}</div></Card>}
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}><div style={{fontWeight:800,fontSize:20,color:C.carltonNavy}}>Performance Results</div><Btn small onClick={()=>setView("metrics")}>⚙️ Metrics</Btn></div>
          {Object.entries(displayMetrics).map(([cat,ms])=>(<div key={cat}><SectionHead title={cat} color={CAT_COLORS[cat]||C.purple} count={ms.length}/>{ms.map(m=>m.bi?<BilateralCard key={m.id} m={m} data={latest} pb={pbs} prev={prev}/>:<UnilateralCard key={m.id} m={m} data={latest} pb={pbs} prev={prev}/>)}</div>))}
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:32,marginBottom:12}}><div style={{fontWeight:700,fontSize:18,color:C.carltonNavy}}>Team Profiling Quadrants</div><Btn small accent onClick={()=>setEditingQuad("new")}>+ Add</Btn></div>
          <div style={{fontSize:11,color:C.textLight,marginBottom:12}}>Each dot = 1 athlete (latest) • Crosshairs = team avg • <span style={{color:C.teal,fontWeight:700}}>★ {cur}</span></div>
          <div style={{display:"flex",gap:12,flexWrap:"wrap"}}>{quadrants.map(q=><TeamQuadrantChart key={q.id} qConfig={q} allAthletes={athletes} currentAthlete={cur} metricMap={metricMap} onEdit={()=>setEditingQuad(q)} onDelete={()=>deleteQuadrant(q.id)}/>)}</div>
          {asymmetries.length>0&&(<><div style={{fontWeight:800,fontSize:20,color:C.carltonNavy,marginTop:32,marginBottom:12}}>Asymmetry Dashboard</div><Card><div style={{display:"flex",gap:16,marginBottom:12,flexWrap:"wrap"}}>{[["Normal (≤10%)",C.green],["Monitor (10-15%)",C.amber],["Flag (>15%)",C.red]].map(([l,c])=>(<div key={l} style={{display:"flex",alignItems:"center",gap:4}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{fontSize:10,color:C.textLight}}>{l}</span></div>))}</div><div style={{display:"flex",gap:12,marginBottom:12}}><span style={{fontSize:12,fontWeight:700,color:C.redDark}}>{asymmetries.filter(a=>a.status==="flag").length} Flag</span><span style={{fontSize:12,fontWeight:700,color:C.amberDark}}>{asymmetries.filter(a=>a.status==="monitor").length} Monitor</span><span style={{fontSize:12,fontWeight:700,color:C.greenDark}}>{asymmetries.filter(a=>a.status==="normal").length} Normal</span></div>{asymmetries.map((a,i)=><AsymRow key={i} name={a.name} l={a.l} r={a.r}/>)}</Card></>)}
        </>)}
      </>)}
      {view==="input"&&(<><div style={{fontWeight:800,fontSize:20,color:C.carltonNavy,marginBottom:4}}>{editIdx!==null?"Edit":"Manual Entry"}</div><div style={{fontSize:12,color:C.textLight,marginBottom:16}}><span style={{color:C.teal,cursor:"pointer",fontWeight:600}} onClick={()=>setView("metrics")}>Configure</span> • <span style={{color:C.teal,cursor:"pointer",fontWeight:600}} onClick={()=>setShowImport(true)}>Import CSV</span></div><InputForm metrics={metrics} visibleMetrics={visibleMetrics} onSave={saveSession} existingData={editIdx!==null?sessions[editIdx]:null}/></>)}
      {view==="metrics"&&(<><div style={{fontWeight:800,fontSize:20,color:C.carltonNavy,marginBottom:4}}>Dashboard Metrics</div><div style={{fontSize:12,color:C.textLight,marginBottom:16}}>Toggle visibility or delete with ✕</div><MetricConfig metrics={metrics} visibleMetrics={visibleMetrics} onUpdateVisible={updateVisible} onDeleteMetric={deleteMetric} allDataMetrics={allDataMetrics}/></>)}
      {view==="history"&&(<><div style={{fontWeight:800,fontSize:20,color:C.carltonNavy,marginBottom:16}}>Session History</div>{sessions.length===0?<Card style={{textAlign:"center",padding:32,color:C.textLight}}>No sessions.</Card>:sessions.slice().reverse().map((s,ri)=>{const i=sessions.length-1-ri,filled=Object.keys(s).filter(k=>k!=="date"&&k!=="notes"&&s[k]!=null).length;return(<Card key={i} style={{marginBottom:8,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{flex:1}}><div style={{fontWeight:700,color:C.carltonNavy,fontSize:14}}>{s.date}{i===sessions.length-1&&<span style={{fontSize:10,background:C.tealLight,color:"#fff",padding:"1px 8px",borderRadius:8,marginLeft:6}}>Latest</span>}</div><div style={{fontSize:11,color:C.textLight,marginTop:2}}>{filled} metrics</div></div><div style={{display:"flex",gap:6,flexShrink:0}}><Btn small onClick={()=>{setEditIdx(i);setView("input");}}>Edit</Btn><Btn small danger onClick={()=>{if(confirm("Delete?"))delSession(i);}}>Delete</Btn></div></Card>);})}</>)}
    </div></>)}
    <div style={{textAlign:"center",padding:"20px 16px 32px",fontSize:11,color:C.textLight}}>Carlton AFLW Performance Reconditioning • Powered by Calibre.</div>
  </div>);
}
